# Tipografia
font_family JetBrainsMono Nerd Font
	bold_font auto
	italic_font auto
	bold_italic_font auto
font_size 11

# Opacidad
background_opacity 0.95

# Fondo y texto
background            #000000
foreground            #FFFFFF

# Cursor
cursor                #FFFFFF
cursor_text_color     #000000

# Selección
selection_background  #555555
selection_foreground  #FFFFFF

# URLs
url_color             #B0B0B0

# Negro
color0                #000000
color8                #404040

# Rojo
color1                #5A5A5A
color9                #7A7A7A

# Verde
color2                #6A6A6A
color10               #8A8A8A

# Amarillo
color3                #808080
color11               #A0A0A0

# Azul
color4                #969696
color12               #B6B6B6

# Magenta
color5                #ACACAC
color13               #CCCCCC

# Cian
color6                #C0C0C0
color14               #E0E0E0

# Blanco
color7                #D8D8D8
color15               #FFFFFF
