allow_remote_control yes
# Tipografia
font_family JetBrainsMono Nerd Font
	bold_font auto
	italic_font auto
	bold_italic_font auto
font_size 11

# Opacidad
background_opacity 0.4

# Colores de texto plano y fondo
background #080808
foreground #ffffff

# Colores de selección de texto
selection_background #438E66
selection_foreground #000000

#Color de URLs
url_color #B9D674


# Negro
color0  #21222C
color8  #6272A4

# Rojo
color1  #99C29E
color9  #FF6E6E

# Verde
color2  #50FA7B
color10 #69FF94

# Amarillo
color3  #7CB183
color11 #9ed0a5

# Azul
color4  #44BBB9
color12 #34908f

# Magenta
color5  #F1FA8C
color13 #FF92DF

# Cian
color6  #609F9D
color14 #588886

# Blanco
color7  #F8F8F2
color15 #FFFFFF
