allow_remote_control yes
# Tipografia
font_family JetBrainsMono Nerd Font
	bold_font auto
	italic_font auto
	bold_italic_font auto
font_size 11

# Opacidad
background_opacity 0.4

# Fondo y texto
background            #00020E
foreground            #EAFBFF

# Cursor
cursor                #56C1F8
cursor_text_color     #00020E

# Selección
selection_background  #177BCF
selection_foreground  #FFFFFF

# URLs
url_color             #56C1F8

# Negro
color0                #00020E
color8                #0F1B34

# Rojo (Azul oscuro)
color1                #31a2ff
color9                #1A5E94

# Verde (Cian)
color2                #177BCF
color10               #3ABFDA

# Amarillo (Celeste brillante)
color3                #2EA9E8
color11               #56C1F8

# Azul
color4                #177BCF
color12               #56C1F8

# Magenta (Azul claro)
color5                #3ABFDA
color13               #7FD8FF

# Cian
color6                #56C1F8
color14               #A7E9FF

# Blanco
color7                #D7F7FF
color15               #FFFFFF
