allow_remote_control yes

background_opacity 0.8

font_family Libertinus Mono
font_size 11.5

# Fondo
background            #050505
foreground            #F2F3F4
selection_background  #3A3B3D
selection_foreground  #FFFFFF

# Cursor
cursor                #FFFFFF
cursor_text_color     #121315

# URL
url_color             #D6D8DB

# Colores normales
color0   #0A0B0D   # Negro
color1   #5B5D60   # Gris oscuro
color2   #737578   # Gris
color3   #8D8F92   # Gris claro
color4   #A7A9AC   # Plata
color5   #C0C3C6   # Plata clara
color6   #D7DADD   # Casi blanco
color7   #F2F3F4   # Blanco suave

# Colores brillantes
color8   #1A1B1D
color9   #6C6E71
color10  #87898C
color11  #A3A5A8
color12  #BEC1C4
color13  #D8DBDE
color14  #ECEEEF
color15  #FFFFFF
