allow_remote_control yes

background_opacity 0.6

font_family JetBrainsMono Nerd Font
font_size 11.5

# Fondo
background            #2E2256
foreground            #FDF2F5
selection_background  #B5A7FB
selection_foreground  #2E2256

# Cursor
cursor                #F81FEA
cursor_text_color     #2E2256

# URL
url_color             #284FED

# Colores normales
color0  #2E2256
color1  #F81FEA
color2  #B5A7FB
color3  #284FED
color4  #284FED
color5  #F81FEA
color6  #B5A7FB
color7  #FDF2F5

# Colores brillantes
color8  #4A3B7C
color9  #FF4EF0
color10 #D1C5FF
color11 #5C7EFF
color12 #6B8CFF
color13 #FF77F5
color14 #E3DBFF
color15 #FFFFFF
