allow_remote_control yes
# Tipografia
font_family JetBrainsMono Nerd Font
	bold_font auto
	italic_font auto
	bold_italic_font auto
font_size 11

# Opacidad
background_opacity 0.4

# Fondo y texto
background            #080808
foreground            #ffffff

# Selección
selection_background  #873E83
selection_foreground  #FEF3C5

# URLs
url_color             #FC6B8F

# Negro
color0                #1A1A1A
color8                #4A4A4A

# Rojo
color1                #FC6B8F
color9                #FF88A8

# Verde
color2                #A7D58B
color10               #C2E7A8

# Amarillo
color3                #FEF3C5
color11               #FFF6D8

# Azul
color4                #4D5086
color12               #6870B0

# Magenta
color5                #873E83
color13               #A55AA3

# Cian
color6                #6F86B7
color14               #8FA6D9

# Blanco
color7                #E8DFC0
color15               #FFFFFF
