# Tipografia
font_family JetBrainsMono Nerd Font
	bold_font auto
	italic_font auto
	bold_italic_font auto
font_size 11

# Opacidad
background_opacity 0.75

# Colores de texto plano y fondo
background #080808
foreground #ffffff

# Colores de selección de texto
selection_background #AB75FF
selection_foreground #000000

#Color de URLs
url_color #B9D674


# Negro
color0  #21222C
color8  #6272A4

# Rojo
color1  #FF5555
color9  #FF6E6E

# Verde
color2  #50FA7B
color10 #69FF94

# Amarillo
color3  #F1FA8C
color11 #FFFFA5

# Azul
color4  #BD93F9
color12 #D6ACFF

# Magenta
color5  #FF79C6
color13 #FF92DF

# Cian
color6  #8BE9FD
color14 #A4FFFF

# Blanco
color7  #F8F8F2
color15 #FFFFFF
